services:
  - type: web
    name: weather-app
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn weather/weather.wsgi:application"
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
      - key: DEBUG
        value: False
      - key: OPENWEATHER_API_KEY
        sync: false 